### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by atmesh** [loomsen/puppet-elkstack#1]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at '.'; expected '}' at /etc/puppet/modules/elkstack/manifests/config.pp:27 on node kibanatest.novalocal
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by loomsen** [comment]
Hi, which puppet version are you using please? Do you have the latest source?

**Comment by atmesh** [comment]
I am using puppet-3.8.7.

**Comment by loomsen** [comment]
Hi, yeah, I'm sorry, but this module only works with puppet >=4.0 or using the future parser maybe. I should add a check for that. Thank you for reporting, but this is just due to the version in use.

**Comment by atmesh** [comment]
Hmm...Thanks
